export const GET_CURRENT_TOURS_START = "TOURS–REDUCER/GET_CURRENT_TOURS_START";
export const GET_CURRENT_TOURS_SUCCESS =
  "TOURS–REDUCER/GET_CURRENT_TOURS_SUCCESS";
export const GET_CURRENT_TOURS_FAILED =
  "TOURS–REDUCER/GET_CURRENT_TOURS_FAILED";

export const DELETE_CHOSEN_TOUR = "TOURS–REDUCER/DELETE_CHOSEN_TOUR";

export const TOGGLE_LOADER = "TOURS–REDUCER/TOGGLE_LOADER";
